on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: Azure/docker-login@v1
      with:
        login-server: chenyecrnew.azurecr.cn
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t chenyecrnew.azurecr.cn/k8sdemo:${{ github.sha }}
        docker push chenyecrnew.azurecr.cn/k8sdemo:${{ github.sha }}

    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: chenyecrnew
        resource-group: chenyerg

    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: chenyecrnew.azurecr.cn
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          demo.azurecr.cn/k8sdemo:${{ github.sha }}
        imagepullsecrets: |
          demo-k8s-secret
